export { OnboardingWrapper } from "./layouts/OnboardingWrapper"
// export { DashboardWrapper } from "./layouts/DashboardWrapper"
export { Button, IconButton, LinkButton, TextButton } from "./forms/FormButtons"
export { IconLink, TextLink } from "./forms/Links"
export { Input, PrefixInput, CheckboxInput, TextareaInput, Label } from "./forms/Inputs"
export { Card } from "./custom/Card"

// typography
export { Display1 } from "./typography/Display1"
export { Display2 } from "./typography/Display2"
export { H1 } from "./typography/H1"
export { H2 } from "./typography/H2"
export { H3 } from "./typography/H3"
export { H4 } from "./typography/H4"
export { H5 } from "./typography/H5"
export { H6 } from "./typography/H6"
export { SubHeading } from "./typography/SubHeading"
export { FootText } from "./typography/FootText"
export { Caption } from "./typography/Caption"
export { P1 } from "./typography/P1"
export { P2 } from "./typography/P2"
export { P3 } from "./typography/P3"
